{% set name = "gwcosmo" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwcosmo-{{ version }}.tar.gz
  sha256: af0b2642b64056d1c63096d6bdf35b5e07fe5b76c8942827cf05b4f239612fb8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - astropy
    - bilby
    - h5py
    - healpy
    - lalsuite
    - ligo-gracedb
    - ligo-segments
    - ligo.skymap <=1.0.7
    - lscsoft-glue
    - matplotlib-base >=2.0
    - numpy <=1.23.5,>=1.19
    - pandas
    - progressbar
    - scipy
    - seaborn
    - tqdm

test:
  imports:
    - gwcosmo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://lscsoft.docs.ligo.org/gwcosmo/
  summary: A package to estimate cosmological parameters using gravitational-wave observations
  license: GPL-2.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - transientlunatic
    - CChapmanbird
    - rachelmgray
    - jcbayley
